using System.Globalization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Depscan;

/// <summary>
///     Recognizes reference-assembly source - API-surface stubs such as dotnet/runtime's
///     <c>ref/</c> folders, generated by GenAPI, whose every member body is <c>{ throw null; }</c>
///     or empty - and keeps it out of a compilation that also holds the implementation (issue #69).
/// </summary>
/// <remarks>
///     <para>
///         Dosai compiles every file of a tree into one compilation, so a library's
///         <c>ref/ICacheEntry.cs</c> (<c>public partial interface ICacheEntry</c>) and its
///         <c>src/ICacheEntry.cs</c> (<c>public interface ICacheEntry</c>) became one merged type
///         with every member declared twice (CS0102, CS0111, CS0260, ...). A call on such a member
///         binds ambiguously (CS0229), and Roslyn's error recovery resolves that ambiguity
///         differently between runs, so the same tree produced a different call graph from run to
///         run and lost edges outright.
///     </para>
///     <para>
///         Only a reference source's redeclarations of types a non-reference file of the same
///         compilation also declares are left out: a stub that declares nothing else is dropped,
///         one that also declares types nothing else does keeps those, and scanning an
///         API-surface folder on its own keeps all of it. Detection is syntactic and per tree, so
///         it runs with the parse.
///     </para>
/// </remarks>
internal static class ReferenceSources
{
    /// <summary>
    ///     What one parsed tree looks like: whether it is reference source, the types it declares
    ///     (<c>Namespace.Outer`1+Inner`0</c>), and which of those declarations are not partial.
    /// </summary>
    internal sealed record Classification(bool IsReferenceSource, IReadOnlyList<string> DeclaredTypes, IReadOnlyList<string> NonPartialTypes);

    /// <summary>A reference source compiled without its redeclarations of implemented types, and the top-level types it kept.</summary>
    internal sealed record TrimmedSource(CSharpSyntaxTree Tree, IReadOnlyList<string> KeptTypes);

    /// <summary>
    ///     The trees to compile (with their classifications, index-aligned; trimmed reference
    ///     sources in place of their originals), the reference sources left out whole, and the
    ///     trimmed ones.
    /// </summary>
    internal sealed record PartitionResult(List<CSharpSyntaxTree> Kept, List<Classification> KeptClassifications, List<CSharpSyntaxTree> Skipped, List<TrimmedSource> Trimmed);

    internal static Classification Classify(SyntaxTree tree)
    {
        var root = tree.GetRoot();
        var throwNullBodies = 0;
        var realBodies = 0;
        var declaredTypes = new List<string>();
        var nonPartialTypes = new List<string>();
        foreach (var node in root.DescendantNodes())
        {
            switch (node)
            {
                case BaseMethodDeclarationSyntax method:
                    Count(method.Body, method.ExpressionBody, ref throwNullBodies, ref realBodies);
                    break;
                case AccessorDeclarationSyntax accessor:
                    Count(accessor.Body, accessor.ExpressionBody, ref throwNullBodies, ref realBodies);
                    break;
                case PropertyDeclarationSyntax { ExpressionBody: not null } property:
                    Count(null, property.ExpressionBody, ref throwNullBodies, ref realBodies);
                    break;
                case IndexerDeclarationSyntax { ExpressionBody: not null } indexer:
                    Count(null, indexer.ExpressionBody, ref throwNullBodies, ref realBodies);
                    break;
                case LocalFunctionStatementSyntax:
                case GlobalStatementSyntax:
                    realBodies++;
                    break;
                // Code outside a body - a field or property initializer that calls, creates,
                // captures or assigns - is implementation too. Attribute arguments are not.
                case InvocationExpressionSyntax or BaseObjectCreationExpressionSyntax or AnonymousFunctionExpressionSyntax or AssignmentExpressionSyntax
                    when realBodies == 0 && !node.Ancestors().Any(ancestor => ancestor is AttributeSyntax):
                    realBodies++;
                    break;
                case BaseTypeDeclarationSyntax type:
                    var typeKey = TypeKey(type, type.Identifier.ValueText, type is TypeDeclarationSyntax { TypeParameterList: { } parameters } ? parameters.Parameters.Count : 0);
                    declaredTypes.Add(typeKey);
                    if (!type.Modifiers.Any(SyntaxKind.PartialKeyword))
                    {
                        nonPartialTypes.Add(typeKey);
                    }
                    break;
                case DelegateDeclarationSyntax @delegate:
                    var delegateKey = TypeKey(@delegate, @delegate.Identifier.ValueText, @delegate.TypeParameterList?.Parameters.Count ?? 0);
                    declaredTypes.Add(delegateKey);
                    nonPartialTypes.Add(delegateKey);
                    break;
            }
        }

        // GenAPI stamps its output with the API-review header; a stub file whose only members
        // return null (a default interface method) has no `throw null` to recognize it by.
        var reviewedApiSurface = throwNullBodies == 0 && realBodies == 0 && HasApiReviewHeader(root);
        return new Classification(realBodies == 0 && (throwNullBodies > 0 || reviewedApiSurface), declaredTypes, nonPartialTypes);
    }

    /// <summary>
    ///     Splits trees into those to compile and the reference-source trees that only redeclare
    ///     types some other tree implements; a reference source that also declares types nothing
    ///     else does is compiled trimmed to those. Order is preserved. <paramref name="classifications" />,
    ///     when given, is index-aligned with <paramref name="trees" /> (computed during a parallel
    ///     parse); otherwise each tree is classified here.
    /// </summary>
    internal static PartitionResult Partition(IReadOnlyList<CSharpSyntaxTree> trees, IReadOnlyList<Classification>? classifications = null)
    {
        var classified = classifications ?? trees.Select(Classify).ToList();
        var implemented = new HashSet<string>(StringComparer.Ordinal);
        for (var index = 0; index < trees.Count; index++)
        {
            if (!classified[index].IsReferenceSource)
            {
                implemented.UnionWith(classified[index].DeclaredTypes);
            }
        }

        var kept = new List<CSharpSyntaxTree>(trees.Count);
        var keptClassifications = new List<Classification>(trees.Count);
        var skipped = new List<CSharpSyntaxTree>();
        var trimmed = new List<TrimmedSource>();
        for (var index = 0; index < trees.Count; index++)
        {
            var classification = classified[index];
            if (!classification.IsReferenceSource || !classification.DeclaredTypes.Any(implemented.Contains))
            {
                kept.Add(trees[index]);
                keptClassifications.Add(classification);
            }
            else if (TrimImplementedTypes(trees[index], implemented) is { } trimmedSource)
            {
                kept.Add(trimmedSource.Tree);
                keptClassifications.Add(Classify(trimmedSource.Tree));
                trimmed.Add(trimmedSource);
            }
            else
            {
                skipped.Add(trees[index]);
            }
        }

        return new PartitionResult(kept, keptClassifications, skipped, trimmed);
    }

    /// <summary>
    ///     The reference source with its top-level declarations of implemented types blanked out,
    ///     or null when it declares no other type. Blanking replaces each such declaration's
    ///     tokens with spaces and keeps line breaks, comments and preprocessor directives, so the
    ///     directive structure is untouched and every type left keeps its line numbers.
    /// </summary>
    private static TrimmedSource? TrimImplementedTypes(CSharpSyntaxTree tree, HashSet<string> implemented)
    {
        var redeclarations = new List<SyntaxNode>();
        var keptTypes = new List<string>();
        foreach (var node in tree.GetRoot().DescendantNodes(node => node is CompilationUnitSyntax or BaseNamespaceDeclarationSyntax))
        {
            var key = node switch
            {
                BaseTypeDeclarationSyntax type => TypeKey(type, type.Identifier.ValueText, type is TypeDeclarationSyntax { TypeParameterList: { } parameters } ? parameters.Parameters.Count : 0),
                DelegateDeclarationSyntax @delegate => TypeKey(@delegate, @delegate.Identifier.ValueText, @delegate.TypeParameterList?.Parameters.Count ?? 0),
                _ => null
            };
            if (key is null)
            {
                continue;
            }

            if (implemented.Contains(key))
            {
                redeclarations.Add(node);
            }
            else
            {
                keptTypes.Add(key);
            }
        }

        if (keptTypes.Count == 0)
        {
            return null;
        }

        var text = tree.GetText();
        var changes = new List<TextChange>(redeclarations.Count);
        foreach (var declaration in redeclarations)
        {
            var span = declaration.Span;
            var blanked = text.ToString(span).ToCharArray();
            foreach (var token in declaration.DescendantTokens())
            {
                for (var position = token.Span.Start; position < token.Span.End; position++)
                {
                    if (!SyntaxFacts.IsNewLine(blanked[position - span.Start]))
                    {
                        blanked[position - span.Start] = ' ';
                    }
                }
            }

            changes.Add(new TextChange(span, new string(blanked)));
        }

        return new TrimmedSource((CSharpSyntaxTree)tree.WithChangedText(text.WithChanges(changes)), keptTypes);
    }

    /// <summary>
    ///     Slice diagnostics for a partition: the reference sources left out, and the types the
    ///     compiled trees still declare in more than one file without all declarations being
    ///     partial - the same duplicate-member ambiguity, from per-platform or per-target variants
    ///     that no single build compiles together. Both are syntactic, so they cost nothing next
    ///     to binding; the compiler's full declaration-error histogram is under --debug.
    /// </summary>
    internal static IEnumerable<string> Diagnostics(PartitionResult partition, string basePath)
    {
        string Relative(SyntaxTree tree) => Path.GetRelativePath(basePath, tree.FilePath).Replace('\\', '/');

        if (partition.Skipped.Count > 0)
        {
            var examples = string.Join(", ", partition.Skipped.Take(3).Select(Relative));
            yield return string.Create(CultureInfo.InvariantCulture,
                $"Skipped {partition.Skipped.Count} reference-assembly source file(s) (API-surface stubs whose members only `throw null`, such as dotnet/runtime ref/ folders) that only redeclare types implemented elsewhere in the tree, e.g. {examples}. Compiling both declared every member twice, and calls on those members bound ambiguously and differently between runs.");
        }

        if (partition.Trimmed.Count > 0)
        {
            var keptTypes = partition.Trimmed.Sum(trimmed => trimmed.KeptTypes.Count);
            var typeExamples = string.Join(", ", partition.Trimmed.SelectMany(trimmed => trimmed.KeptTypes).Take(3).Select(DisplayName));
            var fileExamples = string.Join(", ", partition.Trimmed.Take(3).Select(trimmed => Relative(trimmed.Tree)));
            yield return string.Create(CultureInfo.InvariantCulture,
                $"Trimmed {partition.Trimmed.Count} reference-assembly source file(s) to the {keptTypes} type(s) that no other file declares, e.g. {typeExamples} (in {fileExamples}): their redeclarations of types implemented elsewhere are left out for the same reason as a skipped stub, and the API surface only they declare is still analyzed.");
        }

        var declaringFiles = new Dictionary<string, List<int>>(StringComparer.Ordinal);
        var nonPartial = new HashSet<string>(StringComparer.Ordinal);
        for (var index = 0; index < partition.Kept.Count; index++)
        {
            var classification = partition.KeptClassifications[index];
            nonPartial.UnionWith(classification.NonPartialTypes);
            foreach (var type in classification.DeclaredTypes.Distinct(StringComparer.Ordinal))
            {
                if (!declaringFiles.TryGetValue(type, out var files))
                {
                    declaringFiles[type] = files = [];
                }

                files.Add(index);
            }
        }

        var duplicates = declaringFiles
            .Where(entry => entry.Value.Count > 1 && nonPartial.Contains(entry.Key))
            .OrderBy(entry => entry.Value[0])
            .ThenBy(entry => entry.Key, StringComparer.Ordinal)
            .ToList();
        if (duplicates.Count > 0)
        {
            var examples = string.Join("; ", duplicates.Take(3).Select(entry =>
                $"{DisplayName(entry.Key)} ({string.Join(", ", entry.Value.Take(3).Select(index => Relative(partition.Kept[index])))})"));
            yield return string.Create(CultureInfo.InvariantCulture,
                $"{duplicates.Count} type(s) are declared by more than one file without all declarations being partial, e.g. {examples}: typically per-platform or per-target variants that no single build compiles together. Dosai compiles every file into one compilation, so such a type's members are declared twice and calls on them bind ambiguously, possibly differently between runs; excluding the variants a build does not use (--exclude) keeps the result stable.");
        }
    }

    /// <summary><c>Ns.Outer`1+Inner`0</c> as <c>Ns.Outer`1.Inner</c>.</summary>
    private static string DisplayName(string key) => key.Replace("`0", string.Empty, StringComparison.Ordinal).Replace('+', '.');

    /// <summary>
    ///     Stub bodies: <c>throw null</c> (counted), and empty or <c>null</c>/<c>default</c>-returning
    ///     ones (neutral - the API surface of a default interface member). Anything else is code.
    /// </summary>
    private static void Count(BlockSyntax? body, ArrowExpressionClauseSyntax? expressionBody, ref int throwNullBodies, ref int realBodies)
    {
        if (expressionBody is not null)
        {
            if (expressionBody.Expression is ThrowExpressionSyntax thrown && IsNullLiteral(thrown.Expression))
            {
                throwNullBodies++;
            }
            else if (!IsNullOrDefault(expressionBody.Expression))
            {
                realBodies++;
            }

            return;
        }

        if (body is null || body.Statements.Count == 0)
        {
            return;
        }

        switch (body.Statements)
        {
            case [ThrowStatementSyntax { Expression: var thrownExpression }] when IsNullLiteral(thrownExpression):
                throwNullBodies++;
                break;
            case [ReturnStatementSyntax { Expression: var returned }] when IsNullOrDefault(returned):
                break;
            default:
                realBodies++;
                break;
        }
    }

    private static bool IsNullLiteral(ExpressionSyntax? expression) =>
        expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.NullLiteralExpression);

    private static bool IsNullOrDefault(ExpressionSyntax? expression) =>
        IsNullLiteral(expression)
        || expression is DefaultExpressionSyntax
        || (expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.DefaultLiteralExpression));

    private static bool HasApiReviewHeader(SyntaxNode root) =>
        root.GetLeadingTrivia().Any(trivia => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                                              && trivia.ToString().Contains("aka.ms/api-review", StringComparison.OrdinalIgnoreCase));

    /// <summary><c>Namespace.Outer`1+Inner`0</c>: namespace, containing types and arity, as the compiler merges declarations.</summary>
    private static string TypeKey(SyntaxNode declaration, string name, int arity)
    {
        var parts = new List<string> { $"{name}`{arity}" };
        foreach (var ancestor in declaration.Ancestors())
        {
            switch (ancestor)
            {
                case TypeDeclarationSyntax containing:
                    parts.Add($"{containing.Identifier.ValueText}`{containing.TypeParameterList?.Parameters.Count ?? 0}+");
                    break;
                case BaseNamespaceDeclarationSyntax @namespace:
                    parts.Add(@namespace.Name.ToString() + ".");
                    break;
            }
        }

        parts.Reverse();
        return string.Concat(parts);
    }
}
