name: build and test

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  preview-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        dotnet: [ '10.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          dotnet-quality: 'preview'
      - name: Restore dependencies
        run: |
          find . -type f \( -name '*.csproj' -o -name '*.vbproj' \) -exec sed -i 's/net9\.0/net10\.0/g' {} +
          dotnet restore
      - name: Build
        run: dotnet build --no-restore ./Dosai
      - name: Test
        run: |
          dotnet test
          dotnet run --project ./Dosai/ methods --path ./Dosai/Dosai.cs
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        dotnet: [ '9.0.x' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
        source-url: https://nuget.pkg.github.com/owasp-dep-scan/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ./Dosai
    - name: Test
      run: |
        dotnet test
        dotnet run --project ./Dosai/ methods --path ./Dosai/Dosai.cs
    - name: Publish binaries
      run: |
        dotnet publish ./Dosai/ -r linux-x64 --property:PublishDir=dosai-linux -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai
        dotnet publish ./Dosai/ -r linux-x64 --property:PublishDir=dosai-linux-amd64 -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-linux-amd64
        dotnet publish ./Dosai/ -r win-x64 --property:PublishDir=dosai-win -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai
        dotnet publish ./Dosai/ -r win-arm64 --property:PublishDir=dosai-win-arm64 -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-windows-arm64
        dotnet publish ./Dosai/ -r osx-x64 --property:PublishDir=dosai-osx -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-osx-x64
        dotnet publish ./Dosai/ -r osx-arm64 --property:PublishDir=dosai-osx-arm64 -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-osx-arm64
        dotnet publish ./Dosai/ -r linux-arm --property:PublishDir=dosai-linux-arm -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-linux-arm
        dotnet publish ./Dosai/ -r linux-arm64 --property:PublishDir=dosai-linux-arm64 -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-linux-arm64
        dotnet publish ./Dosai/ -r linux-musl-x64 --property:PublishDir=dosai-linux-musl-x64 -p:PublishSingleFile=true --self-contained false /p:UseAppHost=true /p:AssemblyName=Dosai-linux-musl-x64
        dotnet publish ./Dosai/ -r linux-x64 --property:PublishDir=dosai-linux-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-full
        dotnet publish ./Dosai/ -r linux-x64 --property:PublishDir=dosai-linux-amd64-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-linux-amd64-full
        dotnet publish ./Dosai/ -r win-x64 --property:PublishDir=dosai-win-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-full
        dotnet publish ./Dosai/ -r win-arm64 --property:PublishDir=dosai-win-arm64-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-windows-arm64-full
        dotnet publish ./Dosai/ -r osx-x64 --property:PublishDir=dosai-osx-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-osx-x64-full
        dotnet publish ./Dosai/ -r osx-arm64 --property:PublishDir=dosai-osx-arm64-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-osx-arm64-full
        dotnet publish ./Dosai/ -r linux-arm --property:PublishDir=dosai-linux-arm-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-linux-arm-full
        dotnet publish ./Dosai/ -r linux-arm64 --property:PublishDir=dosai-linux-arm64-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-linux-arm64-full
        dotnet publish ./Dosai/ -r linux-musl-x64 --property:PublishDir=dosai-linux-musl-x64-full -p:PublishSingleFile=true --self-contained true /p:UseAppHost=true /p:AssemblyName=Dosai-linux-musl-x64-full
    - name: Publish the package
      run: |
        dotnet pack --configuration Release Dosai
        dotnet nuget push --skip-duplicate Dosai/bin/x64/Release/*.nupkg
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Dosai/dosai-linux/Dosai
          Dosai/dosai-linux/Dosai.pdb
          Dosai/dosai-linux-amd64/Dosai-linux-amd64
          Dosai/dosai-linux-amd64/Dosai-linux-amd64.pdb
          Dosai/dosai-win/Dosai.exe
          Dosai/dosai-win-arm64/Dosai-windows-arm64.exe
          Dosai/dosai-osx/Dosai-osx-x64
          Dosai/dosai-osx/Dosai-osx-x64.pdb
          Dosai/dosai-osx-arm64/Dosai-osx-arm64
          Dosai/dosai-osx-arm64/Dosai-osx-arm64.pdb
          Dosai/dosai-linux-arm/Dosai-linux-arm
          Dosai/dosai-linux-arm/Dosai-linux-arm.pdb
          Dosai/dosai-linux-arm64/Dosai-linux-arm64
          Dosai/dosai-linux-arm64/Dosai-linux-arm64.pdb
          Dosai/dosai-linux-musl-x64/Dosai-linux-musl-x64
          Dosai/dosai-linux-musl-x64/Dosai-linux-musl-x64.pdb
          Dosai/dosai-linux-full/Dosai-full
          Dosai/dosai-linux-amd64-full/Dosai-linux-amd64-full
          Dosai/dosai-win-full/Dosai-full.exe
          Dosai/dosai-win-arm64-full/Dosai-windows-arm64-full.exe
          Dosai/dosai-osx-full/Dosai-osx-x64-full
          Dosai/dosai-osx-arm64-full/Dosai-osx-arm64-full
          Dosai/dosai-linux-arm-full/Dosai-linux-arm-full
          Dosai/dosai-linux-arm64-full/Dosai-linux-arm64-full
          Dosai/dosai-linux-musl-x64-full/Dosai-linux-musl-x64-full
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
